# Importing pandas and numpy packages

In [42]:
import pandas as pd  # pandas package
import numpy as np   # numpy package
import matplotlib.pyplot as plt

In [3]:
movie_df = pd.read_csv("data/movie.csv")
ratings_df = pd.read_csv("data/ratings.csv")
user_df = pd.read_csv("data/user.csv")

In [4]:
# get first five records
user_df.head()

   user id  age gender  occupation zip code
0        1   24      M  technician    85711
1        2   53      F       other    94043
2        3   23      M      writer    32067
3        4   24      M  technician    43537
4        5   33      F       other    15213

In [5]:
user_df.head(10)

   user id  age gender     occupation zip code
0        1   24      M     technician    85711
1        2   53      F          other    94043
2        3   23      M         writer    32067
3        4   24      M     technician    43537
4        5   33      F          other    15213
5        6   42      M      executive    98101
6        7   57      M  administrator    91344
7        8   36      M  administrator    05201
8        9   29      M        student    01002
9       10   53      M         lawyer    90703

In [6]:
user_df.head()

   user id  age gender  occupation zip code
0        1   24      M  technician    85711
1        2   53      F       other    94043
2        3   23      M      writer    32067
3        4   24      M  technician    43537
4        5   33      F       other    15213

In [8]:
### Shape/ Dimension of the Data
rows, columns   = user_df.shape
print(f"Users Data Set has (rows) records and (columns) features")

Users Data Set has (rows) records and (columns) features

In [10]:
user_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 943 entries, 0 to 942
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   user id     943 non-null    int64
 1   age         943 non-null    int64
 2   gender      943 non-null    str
 3   occupation  943 non-null    str
 4   zip code    943 non-null    str
dtypes: int64(2), str(3)
memory usage: 37.0 KB

In [11]:
### Returns a list of all columns
user_df.columns

Index(['user id', 'age', 'gender', 'occupation', 'zip code'], dtype='str')

In [12]:
## Targeting Specific columns
user_df['age'].info

<bound method Series.info of 0      24
1      53
2      23
3      24
4      33
       ..
938    26
939    32
940    20
941    48
942    22
Name: age, Length: 943, dtype: int64>

In [13]:
type(user_df['age'])

pandas.Series

In [17]:
# Get data types for specific columns
user_df[["age", "occupation"]].info

<bound method DataFrame.info of      age     occupation
0     24     technician
1     53          other
2     23         writer
3     24     technician
4     33          other
..   ...            ...
938   26        student
939   32  administrator
940   20        student
941   48      librarian
942   22        student

[943 rows x 2 columns]>

In [14]:
# Extracting data frame 
user_df.columns

Index(['user id', 'age', 'gender', 'occupation', 'zip code'], dtype='str')

## Descriptive Stats
MCTS (Mean| Median| Mode)
MoVS (Range, Quartiles, Percentiles, variance, Standard Deviation)

In [25]:
user_df['age'].mean()

np.float64(34.05196182396607)

In [26]:
user_df['age'].median()

np.float64(31.0)

In [27]:
user_df['age'].mode()

0    30
Name: age, dtype: int64

In [28]:
user_df.columns

Index(['user id', 'age', 'gender', 'occupation', 'zip code'], dtype='str')

In [29]:
user_df.describe # Targets the numerical values alone

<bound method NDFrame.describe of      user id  age gender     occupation zip code
0          1   24      M     technician    85711
1          2   53      F          other    94043
2          3   23      M         writer    32067
3          4   24      M     technician    43537
4          5   33      F          other    15213
..       ...  ...    ...            ...      ...
938      939   26      F        student    33319
939      940   32      M  administrator    02215
940      941   20      M        student    97229
941      942   48      F      librarian    78209
942      943   22      M        student    77841

[943 rows x 5 columns]>

In [38]:
user_df.describe()# it targets the numerical values alone

          user id         age
count  943.000000  943.000000
mean   472.000000   34.051962
std    272.364951   12.192740
min      1.000000    7.000000
25%    236.500000   25.000000
50%    472.000000   31.000000
75%    707.500000   43.000000
max    943.000000   73.000000

In [39]:
users_thirty_yrs_old_df = user_df.loc[user_df['age'] == 30]
size = len(users_thirty_yrs_old_df)
print(f"There are (size) workers of age 30")

There are (size) workers of age 30

In [30]:
user_df['age'] == 7

0      False
1      False
2      False
3      False
4      False
       ...
938    False
939    False
940    False
941    False
942    False
Name: age, Length: 943, dtype: bool

In [31]:
user_df.loc [user_df['age'] == 73]

     user id  age gender occupation zip code
480      481   73      M    retired    37771

In [37]:
users_thirty_yrs_old_df.dtypes

user id       int64
age           int64
gender          str
occupation      str
zip code        str
dtype: object

In [ ]:
users_thirty_yrs_old_df.dtypes